# RabbitMQ Deployment, Services, and PersistentVolumeClaim.

# PersistentVolumeClaim for RabbitMQ data.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# ClusterIP Service for internal communication with RabbitMQ.
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
---
# LoadBalancer Service to expose the RabbitMQ Management UI.
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-service
spec:
  selector:
    app: rabbitmq
  type: LoadBalancer
  ports:
    - name: management
      port: 15672
      targetPort: 15672
---
# Deployment for the RabbitMQ instance.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "rabbitmq"
        - name: RABBITMQ_DEFAULT_PASS
          value: "rabbitmq"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        volumeMounts:
        - name: rabbitmq-persistent-storage
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-persistent-storage
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
